//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDienTu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPN
    {
        public long MaPhieuNhap { get; set; }
        public long MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> GiaNhap { get; set; }
        public Nullable<long> ThanhTien { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
