//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDienTu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.PhieuBaoHanhs = new HashSet<PhieuBaoHanh>();
        }
    
        public long SDT { get; set; }
        public string TenKH { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string CMND { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<PhieuBaoHanh> PhieuBaoHanhs { get; set; }
    }
}
