//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDienTu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.CTPNs = new HashSet<CTPN>();
        }
    
        public long MaPhieuNhap { get; set; }
        public Nullable<long> MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<long> TongTien { get; set; }
    
        public virtual ICollection<CTPN> CTPNs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
